---
title: "Assignment 1: Introduction"
author: "Rachel Gonsenhauser"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on Tuesday, January 14th at 1:00 pm.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took a short (4-week) introductory workshop on R through the Data Visualization center at the Duke Library. This briefly introduced me to R, but I still feel extremely inexperienced as I have very little experience coding. I was briefly introduced to GitHub in the Data Bootcamp that John Fay ran during the fall semester, but I also have very little experience in this area. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident about my statistical analysis skills and my ability to communicate the results of data analysis.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am very apprehensive about learning to code and becoming familiar with R. I am not extremely tech savvy so I think it will be a big learning curve for me in the beginning of this course, but I am excited to feel more confident as I go!


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/rachel-gonsenhauser/Environmental_Data_Analytics_2020


